# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_question', models.CharField(max_length=200)),
                ('vote_answer', models.CharField(max_length=200)),
                ('vote_time', models.DateTimeField()),
                ('vote_enumerator', models.IntegerField()),
            ],
            options={
                'db_table': 'vote',
            },
        ),
    ]
