# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20160119_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='total_number_questions',
        ),
    ]
