# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20160119_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_answer', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_answer',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_enumerator',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_id_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Vote'),
        ),
    ]
