# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20160127_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='Votes',
        ),
        migrations.AlterModelTable(
            name='votes',
            table='votes',
        ),
    ]
