# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20160205_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='vote_like',
            field=models.IntegerField(default=0),
        ),
    ]
