# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20160210_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='vote_number',
            field=models.IntegerField(default=0),
        ),
    ]
